includes:
  - configs/s2ef/coll/base.yml

model:
  name: painn
  hidden_channels: 512
  num_layers: 6
  num_rbf: 128
  cutoff: 12.0
  max_neighbors: 50
  scale_file: configs/s2ef/200k/painn/painn_nb6_scaling_factors.pt
  regress_forces: True
  direct_forces: True
  use_pbc: True
  otf_graph: True

optim:
  batch_size: 32 # effective batch size = small datasets: {1, 4, 16, {32}, 64}, OC20-All: {64, 128, {512}, 2048}
  eval_batch_size: 32 # effective batch size = small datasets: {1, 4, 16, {32}, 64}, OC20-All: {64, 128, {512}, 2048}
  num_workers: 6
  lr_initial: 1.e-3
  optimizer: AdamW
  optimizer_params: {"eps": 1.e-7, "weight_decay": 0.000002, "amsgrad": True}
  scheduler: LinearWarmupExponentialDecay
  decay_rate: 0.01
  warmup_steps: 3750
  decay_steps: 4500000
  patience: 5
  factor: 0.9
  cooldown: 5
  max_epochs: 1000
  force_coefficient: 1000
  energy_coefficient: 1
  ema_decay: 0.999
  clip_grad_norm: 10
  loss_force: l2mae
