includes:
  - configs/s2ef/coll/painn/painn.yml
trainer: distill

model:
  hidden_channels: 128
  num_layers: 4
  use_distill: True
  distill_layer_code: U4 # look at painn_small.yml   "num_layers"
  teacher_node_dim: 256
  teacher_edge_dim: 256

teacher_path: checkpoints/2023-05-22-03-29-04-s2ef-coll-painn-painn---model.hidden_channels=256/checkpoint.pt
teacher_model:
  name: painn
  hidden_channels: 256
  num_layers: 6
  num_rbf: 128
  cutoff: 12.0
  max_neighbors: 50
  # scale_file: configs/s2ef/200k/painn/painn_nb6_scaling_factors.pt
  regress_forces: True
  direct_forces: True
  use_pbc: True
  otf_graph: True
  use_distill: True
  id_mapping: True
  distill_layer_code: U6
