includes:
  - configs/s2ef/200k/schnet/schnet_base_distill.yml
distillation:
    distill_loss: random_jitter_distill_loss
    adversarial_distill_loss: vec2vec_distill_loss
    adversarial_distill_lambda: 1.0
    distill_lambda: 1.0
    random_std: 0.1
optim:
  batch_size: 32
