includes:
  - configs/s2ef/2M/painn/painn_small.yml
trainer: distill

model:
  use_distill: True
  distill_layer_code: U4 # look at painn_small.yml   "num_layers"
  teacher_node_dim: 512
  teacher_edge_dim: 512

teacher_path: pretrained/painn_h512_s2ef_2M.pt
teacher_model:
  name: painn
  hidden_channels: 512
  num_layers: 6
  num_rbf: 128
  cutoff: 12.0
  max_neighbors: 50
  scale_file: configs/s2ef/200k/painn/painn_nb6_scaling_factors.pt
  regress_forces: True
  direct_forces: True
  use_pbc: True
  otf_graph: True
  use_distill: True
  id_mapping: True
  distill_layer_code: U6
