includes:
  - configs/s2ef/2M/painn/painn_base_distill.yml
trainer: distill
distillation:
    distill_loss: random_jitter_distill_loss
    distill_lambda: 1.0
    adversarial_distill_lambda: 1.0
    adversarial_distill_loss: vec2vec_distill_loss
    random_fixed_length: True
    adversarial_alpha: 0.2
    force_coefficient: 100


optim:
    batch_size: 16
