includes:
  - configs/s2ef/2M/painn/painn_base_distill.yml
distillation:
  distill_loss: edge2node_distill_loss
  distill_lambda: 0.05  # always worse than baselin with lambda 0.05, 0.01, 0.001 (close)
