includes:
  - configs/s2ef/2M/painn/painn_base_distill.yml
trainer: distill
distillation:
    distill_loss: random_jitter_distill_loss
    adversarial_distill_loss: vec2vec_distill_loss
    adversarial_distill_lambda: 1.0
    distill_lambda: 1.0
    random_std: 0.1


optim:
  batch_size: 16
