includes:
  - configs/s2ef/2M/painn/painn_base_distill.yml

distillation:
  distill_loss: node2node_distill_loss_d1M
  distill_lambda: 10000.0
  loss_weighting_synthetic: 0.2 # weighting ratio synth to DFT. Unused if 1

teacher_model:
  distill_final_features: False

dataset:
  - src: data/s2ef/merged_2M_d1M/train/
    normalize_labels: True
    target_mean: -0.7554450631141663
    target_std: 2.887317180633545
    grad_target_mean: 0.0
    grad_target_std: 2.887317180633545
    target_ratio_synthetic: 0.2  # how many of the samples to be from d1M
  - src: data/s2ef/val_id_sample
