includes:
  - configs/s2ef/2M/painn/painn_h512_adversarial_jitter.yml
distillation:
    enable_pgd: True
    pgd_ball: False
    adversarial_init_sd: 0
    energy_coefficient: 0
    adversarial_teacher_grad: True
